import React, {useEffect, useMemo, useState} from 'react';
import {createRoot} from 'react-dom/client';
import {LayoutDashboard, Users, CalendarDays, Sparkles, BarChart3, Settings, Search, Bell, Plus, ArrowUpRight, Clock3, CheckCircle2, MoreHorizontal, WandSparkles, Play, ChevronRight, Image as ImageIcon, Camera, Video, X} from 'lucide-react';
import './styles.css';

const seedModels=[
 {id:1,name:'Mia Laurent',handle:'@mialaurent.ai',niche:'Slow beauty & wellness',status:'Active',color:'#f1c8bc',avatar:'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=400&auto=format&fit=crop',followers:'12.8K',growth:'+18.4%',posts:42,bio:'Coffee, skincare and quiet Tallinn mornings.',traits:['warm','minimal','curious']},
 {id:2,name:'Sofia Vale',handle:'@sofiavale.fit',niche:'Fitness & mindset',status:'Active',color:'#cbd7b7',avatar:'https://images.unsplash.com/photo-1531123897727-8f129e1688ce?w=400&auto=format&fit=crop',followers:'8.4K',growth:'+12.1%',posts:31,bio:'Strong routines for a softer life.',traits:['bold','focused','supportive']},
 {id:3,name:'Lina Nord',handle:'@linanord.home',niche:'Nordic home & lifestyle',status:'Draft',color:'#c8d7df',avatar:'https://images.unsplash.com/photo-1524250502761-1ac6f2e30d43?w=400&auto=format&fit=crop',followers:'—',growth:'Ready',posts:7,bio:'Small rituals and bright northern spaces.',traits:['calm','visual','thoughtful']}
];
const seedPosts=[
 {id:1,model:'Mia Laurent',title:'Slow Sunday skincare ritual',platform:'Instagram',type:'Carousel',when:'Today, 18:30',status:'Ready',accent:'#e9b9aa'},
 {id:2,model:'Sofia Vale',title:'3-minute morning mobility',platform:'TikTok',type:'Video',when:'Tomorrow, 09:00',status:'Review',accent:'#b7c99c'},
 {id:3,model:'Mia Laurent',title:'Tallinn coffee diary',platform:'Instagram',type:'Reel',when:'Jul 14, 12:00',status:'Idea',accent:'#e9b9aa'},
 {id:4,model:'Lina Nord',title:'A quiet reading corner',platform:'Pinterest',type:'Image',when:'Jul 15, 17:00',status:'Draft',accent:'#b9ced8'}
];

function useLocal(key,initial){const [v,setV]=useState(()=>{try{return JSON.parse(localStorage.getItem(key))||initial}catch{return initial}});useEffect(()=>localStorage.setItem(key,JSON.stringify(v)),[key,v]);return [v,setV]}

const nav=[['Overview',LayoutDashboard],['AI Models',Users],['Content Studio',Sparkles],['Calendar',CalendarDays],['Analytics',BarChart3],['Settings',Settings]];
function Sidebar({page,setPage}){return <aside className="sidebar"><div className="brand"><div className="brandmark">A</div><div><b>ATLAS</b><span>AI OPERATING SYSTEM</span></div></div><nav>{nav.map(([n,I])=><button key={n} className={page===n?'active':''} onClick={()=>setPage(n)}><I size={18}/>{n}{n==='Content Studio'&&<i>3</i>}</button>)}</nav><div className="sidebar-bottom"><div className="usage"><span><Sparkles size={15}/> Creative credits</span><b>72%</b><div><i/></div><small>7,240 of 10,000 remaining</small></div><button className="profile"><span>PZ</span><div><b>Pavel</b><small>Workspace owner</small></div><MoreHorizontal size={18}/></button></div></aside>}
function Header({page}){return <header><div><small>ATLAS WORKSPACE</small><h1>{page}</h1></div><div className="header-actions"><label><Search size={17}/><input placeholder="Search anything…"/><kbd>⌘ K</kbd></label><button className="icon"><Bell size={19}/><i/></button><button className="create"><Plus size={18}/> Create</button></div></header>}
function ModelCard({m,onClick}){return <article className="model-card" onClick={onClick}><div className="cover" style={{background:`linear-gradient(135deg,${m.color},#f8f4ed)`}}><img src={m.avatar}/><span className={'state '+m.status.toLowerCase()}>{m.status}</span><button><MoreHorizontal size={18}/></button></div><div className="model-body"><div className="model-title"><div><h3>{m.name}</h3><span>{m.handle}</span></div><ArrowUpRight size={18}/></div><p>{m.niche}</p><div className="model-stats"><span><b>{m.followers}</b><small>Followers</small></span><span><b>{m.growth}</b><small>30d growth</small></span><span><b>{m.posts}</b><small>Posts</small></span></div></div></article>}
function Overview({models,setPage}){return <><section className="hero"><div><span className="eyebrow"><Sparkles size={14}/> SATURDAY, JULY 11</span><h2>Your creative universe<br/>is <em>growing.</em></h2><p>Three digital creators are building their stories.<br/>Here’s what needs your attention today.</p><button onClick={()=>setPage('Content Studio')}><WandSparkles size={18}/> Start creating</button></div><div className="orbit"><div className="orb one"><img src={models[0].avatar}/></div><div className="orb two"><img src={models[1].avatar}/></div><div className="orb three"><img src={models[2].avatar}/></div><div className="center"><Sparkles/></div></div></section><section className="metrics"><div><span>ACTIVE MODELS</span><b>{models.filter(x=>x.status==='Active').length}</b><small><i>+1</i> this month</small></div><div><span>CONTENT THIS WEEK</span><b>18</b><small>12 published · 6 ready</small></div><div><span>TOTAL REACH</span><b>284K</b><small><i>↑ 24%</i> vs last week</small></div><div><span>ENGAGEMENT</span><b>6.8%</b><small><i>↑ 1.2%</i> vs last week</small></div></section><div className="section-head"><div><small>YOUR DIGITAL TALENT</small><h2>AI Models</h2></div><button onClick={()=>setPage('AI Models')}>View all <ChevronRight size={16}/></button></div><section className="model-grid">{models.map(m=><ModelCard key={m.id} m={m}/>)}</section><Queue/></>}
function Queue(){return <section className="queue"><div className="section-head"><div><small>PRODUCTION LINE</small><h2>Today’s queue</h2></div><button>Open calendar <ChevronRight size={16}/></button></div><div className="queue-grid"><div className="next"><span><Clock3 size={15}/> NEXT TO PUBLISH · 18:30</span><h3>Slow Sunday skincare ritual</h3><p>Mia Laurent · Instagram carousel</p><button><Play size={15} fill="currentColor"/> Preview post</button></div><div className="tasks"><p><span><CheckCircle2/> Caption approved</span><b>Ready</b></p><p><span><ImageIcon/> 6 visuals generated</span><b>Ready</b></p><p><span><Camera/> Publishing connection</span><b className="warn">Check</b></p></div></div></section>}
function Models({models,setModels}){const [open,setOpen]=useState(false);const [selected,setSelected]=useState(null);function add(e){e.preventDefault();const f=new FormData(e.currentTarget);setModels([...models,{id:Date.now(),name:f.get('name'),handle:'@'+f.get('name').toLowerCase().replaceAll(' ',''),niche:f.get('niche'),status:'Draft',color:'#d9c9e8',avatar:'https://images.unsplash.com/photo-1544005313-94ddf0286df2?w=400&auto=format&fit=crop',followers:'—',growth:'New',posts:0,bio:'New digital creator.',traits:['original','curious']}]);setOpen(false)}return <><div className="page-title"><div><p>Build consistent digital identities that people remember.</p></div><button className="create" onClick={()=>setOpen(true)}><Plus size={18}/> New AI model</button></div><section className="model-grid large">{models.map(m=><ModelCard key={m.id} m={m} onClick={()=>setSelected(m)}/>)}</section>{(open||selected)&&<div className="modal-wrap" onClick={()=>{setOpen(false);setSelected(null)}}><div className="modal" onClick={e=>e.stopPropagation()}><button className="close" onClick={()=>{setOpen(false);setSelected(null)}}><X/></button>{selected?<><img className="detail-avatar" src={selected.avatar}/><small>DIGITAL CREATOR</small><h2>{selected.name}</h2><p>{selected.bio}</p><div className="chips">{selected.traits.map(x=><span>{x}</span>)}</div><hr/><h3>Identity foundation</h3><p><b>Niche:</b> {selected.niche}</p><p><b>Handle:</b> {selected.handle}</p><button className="primary">Open full identity</button></>:<form onSubmit={add}><small>NEW DIGITAL TALENT</small><h2>Create AI model</h2><label>Name<input name="name" required placeholder="e.g. Emma Stone"/></label><label>Content niche<input name="niche" required placeholder="e.g. Travel & slow living"/></label><label>Primary goal<select><option>Grow an audience</option><option>Brand collaborations</option><option>Sell digital products</option></select></label><button className="primary">Create identity</button></form>}</div></div>}</>}
function Studio({posts,setPosts,models}){const [filter,setFilter]=useState('All');const visible=useMemo(()=>filter==='All'?posts:posts.filter(p=>p.status===filter),[posts,filter]);function generate(){setPosts([{id:Date.now(),model:models[0].name,title:'Fresh morning ritual idea',platform:'Instagram',type:'Reel',when:'Unscheduled',status:'Idea',accent:models[0].color},...posts])}return <><div className="studio-banner"><div><span><WandSparkles/> AI CONTENT STUDIO</span><h2>Turn one idea into a week of content.</h2><p>Choose a creator, set the goal and Atlas prepares the concept, caption, shot list and visual prompt.</p></div><button onClick={generate}><Sparkles/> Generate content</button></div><div className="tabs">{['All','Idea','Draft','Review','Ready'].map(x=><button className={filter===x?'active':''} onClick={()=>setFilter(x)}>{x}</button>)}</div><section className="content-table"><div className="table-head"><span>CONTENT</span><span>CREATOR</span><span>PLATFORM</span><span>SCHEDULE</span><span>STATUS</span></div>{visible.map(p=><div className="table-row" key={p.id}><span className="content-name"><i style={{background:p.accent}}>{p.type==='Video'||p.type==='Reel'?<Video/>:<ImageIcon/>}</i><b>{p.title}<small>{p.type}</small></b></span><span>{p.model}</span><span>{p.platform}</span><span>{p.when}</span><span><b className={'pill '+p.status.toLowerCase()}>{p.status}</b></span></div>)}</section></>}
function Placeholder({page}){return <div className="placeholder"><div><Sparkles/></div><h2>{page} is ready for the next module</h2><p>The foundation is in place. This workspace will connect to real publishing and analytics APIs in the next stage.</p><button className="primary">Plan this module</button></div>}
function App(){const [page,setPage]=useState('Overview');const [models,setModels]=useLocal('atlas-models',seedModels);const [posts,setPosts]=useLocal('atlas-posts',seedPosts);return <div className="app"><Sidebar page={page} setPage={setPage}/><main><Header page={page}/><div className="content">{page==='Overview'?<Overview models={models} setPage={setPage}/>:page==='AI Models'?<Models models={models} setModels={setModels}/>:page==='Content Studio'?<Studio posts={posts} setPosts={setPosts} models={models}/>:<Placeholder page={page}/>}</div></main></div>}
createRoot(document.getElementById('root')).render(<App/>);
