import React, {useEffect, useMemo, useState} from 'react';
import {createRoot} from 'react-dom/client';
import {LayoutDashboard, Users, CalendarDays, Sparkles, BarChart3, Settings, Search, Bell, Plus, ArrowUpRight, Clock3, CheckCircle2, MoreHorizontal, WandSparkles, Play, ChevronRight, Image as ImageIcon, Camera, Video, X} from 'lucide-react';
import './styles.css';

const seedModels=[
 {id:1,name:'Миа Лоран',handle:'@mialaurent.ai',niche:'Красота и осознанная жизнь',status:'Активна',color:'#f1c8bc',avatar:'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=400&auto=format&fit=crop',followers:'12,8 тыс.',growth:'+18,4%',posts:42,bio:'Кофе, уход за собой и тихие таллиннские утра.',traits:['тёплая','минималистичная','любознательная']},
 {id:2,name:'София Вейл',handle:'@sofiavale.fit',niche:'Фитнес и мышление',status:'Активна',color:'#cbd7b7',avatar:'https://images.unsplash.com/photo-1531123897727-8f129e1688ce?w=400&auto=format&fit=crop',followers:'8,4 тыс.',growth:'+12,1%',posts:31,bio:'Сильные привычки для спокойной жизни.',traits:['смелая','целеустремлённая','поддерживающая']},
 {id:3,name:'Лина Норд',handle:'@linanord.home',niche:'Скандинавский дом и стиль жизни',status:'Черновик',color:'#c8d7df',avatar:'https://images.unsplash.com/photo-1524250502761-1ac6f2e30d43?w=400&auto=format&fit=crop',followers:'—',growth:'Готова',posts:7,bio:'Маленькие ритуалы и светлые северные пространства.',traits:['спокойная','визуальная','вдумчивая']}
];
const seedPosts=[
 {id:1,model:'Миа Лоран',title:'Воскресный ритуал ухода за кожей',platform:'Instagram',type:'Карусель',when:'Сегодня, 18:30',status:'Готово',accent:'#e9b9aa'},
 {id:2,model:'София Вейл',title:'Трёхминутная утренняя разминка',platform:'TikTok',type:'Видео',when:'Завтра, 09:00',status:'Проверка',accent:'#b7c99c'},
 {id:3,model:'Миа Лоран',title:'Кофейный дневник Таллинна',platform:'Instagram',type:'Reels',when:'14 июля, 12:00',status:'Идея',accent:'#e9b9aa'},
 {id:4,model:'Лина Норд',title:'Тихий уголок для чтения',platform:'Pinterest',type:'Изображение',when:'15 июля, 17:00',status:'Черновик',accent:'#b9ced8'}
];

function useLocal(key,initial){const [v,setV]=useState(()=>{try{return JSON.parse(localStorage.getItem(key))||initial}catch{return initial}});useEffect(()=>localStorage.setItem(key,JSON.stringify(v)),[key,v]);return [v,setV]}

const nav=[['Главная',LayoutDashboard],['AI-модели',Users],['Контент-студия',Sparkles],['Календарь',CalendarDays],['Аналитика',BarChart3],['Настройки',Settings]];
function Sidebar({page,setPage}){return <aside className="sidebar"><div className="brand"><div className="brandmark">A</div><div><b>ATLAS</b><span>ОПЕРАЦИОННАЯ СИСТЕМА AI</span></div></div><nav>{nav.map(([n,I])=><button key={n} className={page===n?'active':''} onClick={()=>setPage(n)}><I size={18}/>{n}{n==='Контент-студия'&&<i>3</i>}</button>)}</nav><div className="sidebar-bottom"><div className="usage"><span><Sparkles size={15}/> Кредиты генерации</span><b>72%</b><div><i/></div><small>Осталось 7 240 из 10 000</small></div><button className="profile"><span>PZ</span><div><b>Павел</b><small>Владелец пространства</small></div><MoreHorizontal size={18}/></button></div></aside>}
function Header({page}){return <header><div><small>РАБОЧЕЕ ПРОСТРАНСТВО ATLAS</small><h1>{page}</h1></div><div className="header-actions"><label><Search size={17}/><input placeholder="Поиск…"/><kbd>⌘ K</kbd></label><button className="icon"><Bell size={19}/><i/></button><button className="create"><Plus size={18}/> Создать</button></div></header>}
function ModelCard({m,onClick}){return <article className="model-card" onClick={onClick}><div className="cover" style={{background:`linear-gradient(135deg,${m.color},#f8f4ed)`}}><img src={m.avatar}/><span className={'state '+m.status.toLowerCase()}>{m.status}</span><button><MoreHorizontal size={18}/></button></div><div className="model-body"><div className="model-title"><div><h3>{m.name}</h3><span>{m.handle}</span></div><ArrowUpRight size={18}/></div><p>{m.niche}</p><div className="model-stats"><span><b>{m.followers}</b><small>Подписчики</small></span><span><b>{m.growth}</b><small>Рост за 30 дней</small></span><span><b>{m.posts}</b><small>Публикации</small></span></div></div></article>}
function Overview({models,setPage}){return <><section className="hero"><div><span className="eyebrow"><Sparkles size={14}/> СУББОТА, 11 ИЮЛЯ</span><h2>Твоя творческая вселенная<br/><em>растёт.</em></h2><p>Три цифровых автора создают свои истории.<br/>Вот что требует твоего внимания сегодня.</p><button onClick={()=>setPage('Контент-студия')}><WandSparkles size={18}/> Создать контент</button></div><div className="orbit"><div className="orb one"><img src={models[0].avatar}/></div><div className="orb two"><img src={models[1].avatar}/></div><div className="orb three"><img src={models[2].avatar}/></div><div className="center"><Sparkles/></div></div></section><section className="metrics"><div><span>АКТИВНЫЕ МОДЕЛИ</span><b>{models.filter(x=>x.status==='Активна').length}</b><small><i>+1</i> за месяц</small></div><div><span>КОНТЕНТ ЗА НЕДЕЛЮ</span><b>18</b><small>12 опубликовано · 6 готово</small></div><div><span>ОБЩИЙ ОХВАТ</span><b>284 тыс.</b><small><i>↑ 24%</i> к прошлой неделе</small></div><div><span>ВОВЛЕЧЁННОСТЬ</span><b>6,8%</b><small><i>↑ 1,2%</i> к прошлой неделе</small></div></section><div className="section-head"><div><small>ТВОИ ЦИФРОВЫЕ АВТОРЫ</small><h2>AI-модели</h2></div><button onClick={()=>setPage('AI-модели')}>Показать все <ChevronRight size={16}/></button></div><section className="model-grid">{models.map(m=><ModelCard key={m.id} m={m}/>)}</section><Queue/></>}
function Queue(){return <section className="queue"><div className="section-head"><div><small>ЛИНИЯ ПРОИЗВОДСТВА</small><h2>Очередь на сегодня</h2></div><button>Открыть календарь <ChevronRight size={16}/></button></div><div className="queue-grid"><div className="next"><span><Clock3 size={15}/> СЛЕДУЮЩАЯ ПУБЛИКАЦИЯ · 18:30</span><h3>Воскресный ритуал ухода за кожей</h3><p>Миа Лоран · карусель Instagram</p><button><Play size={15} fill="currentColor"/> Предпросмотр</button></div><div className="tasks"><p><span><CheckCircle2/> Текст согласован</span><b>Готово</b></p><p><span><ImageIcon/> Создано 6 изображений</span><b>Готово</b></p><p><span><Camera/> Подключение публикации</span><b className="warn">Проверить</b></p></div></div></section>}
function Models({models,setModels}){const [open,setOpen]=useState(false);const [selected,setSelected]=useState(null);function add(e){e.preventDefault();const f=new FormData(e.currentTarget);setModels([...models,{id:Date.now(),name:f.get('name'),handle:'@'+f.get('name').toLowerCase().replaceAll(' ',''),niche:f.get('niche'),status:'Черновик',color:'#d9c9e8',avatar:'https://images.unsplash.com/photo-1544005313-94ddf0286df2?w=400&auto=format&fit=crop',followers:'—',growth:'Новая',posts:0,bio:'Новый цифровой автор.',traits:['оригинальная','любознательная']}]);setOpen(false)}return <><div className="page-title"><div><p>Создавай последовательные цифровые личности, которых запоминают.</p></div><button className="create" onClick={()=>setOpen(true)}><Plus size={18}/> Новая AI-модель</button></div><section className="model-grid large">{models.map(m=><ModelCard key={m.id} m={m} onClick={()=>setSelected(m)}/>)}</section>{(open||selected)&&<div className="modal-wrap" onClick={()=>{setOpen(false);setSelected(null)}}><div className="modal" onClick={e=>e.stopPropagation()}><button className="close" onClick={()=>{setOpen(false);setSelected(null)}}><X/></button>{selected?<><img className="detail-avatar" src={selected.avatar}/><small>ЦИФРОВОЙ АВТОР</small><h2>{selected.name}</h2><p>{selected.bio}</p><div className="chips">{selected.traits.map(x=><span>{x}</span>)}</div><hr/><h3>Основа личности</h3><p><b>Ниша:</b> {selected.niche}</p><p><b>Имя профиля:</b> {selected.handle}</p><button className="primary">Открыть полный профиль</button></>:<form onSubmit={add}><small>НОВЫЙ ЦИФРОВОЙ АВТОР</small><h2>Создать AI-модель</h2><label>Имя<input name="name" required placeholder="Например, Эмма Лейн"/></label><label>Контентная ниша<input name="niche" required placeholder="Например, путешествия и slow living"/></label><label>Основная цель<select><option>Набирать аудиторию</option><option>Рекламные интеграции</option><option>Продажа цифровых продуктов</option></select></label><button className="primary">Создать личность</button></form>}</div></div>}</>}
function Studio({posts,setPosts,models}){const [filter,setFilter]=useState('Все');const visible=useMemo(()=>filter==='Все'?posts:posts.filter(p=>p.status===filter),[posts,filter]);function generate(){setPosts([{id:Date.now(),model:models[0].name,title:'Идея свежего утреннего ритуала',platform:'Instagram',type:'Reels',when:'Не запланировано',status:'Идея',accent:models[0].color},...posts])}return <><div className="studio-banner"><div><span><WandSparkles/> AI-КОНТЕНТ-СТУДИЯ</span><h2>Преврати одну идею в неделю контента.</h2><p>Выбери автора и цель — Atlas подготовит концепцию, текст, список кадров и визуальный промпт.</p></div><button onClick={generate}><Sparkles/> Создать контент</button></div><div className="tabs">{['Все','Идея','Черновик','Проверка','Готово'].map(x=><button className={filter===x?'active':''} onClick={()=>setFilter(x)}>{x}</button>)}</div><section className="content-table"><div className="table-head"><span>КОНТЕНТ</span><span>АВТОР</span><span>ПЛАТФОРМА</span><span>ПУБЛИКАЦИЯ</span><span>СТАТУС</span></div>{visible.map(p=><div className="table-row" key={p.id}><span className="content-name"><i style={{background:p.accent}}>{p.type==='Видео'||p.type==='Reels'?<Video/>:<ImageIcon/>}</i><b>{p.title}<small>{p.type}</small></b></span><span>{p.model}</span><span>{p.platform}</span><span>{p.when}</span><span><b className={'pill '+p.status.toLowerCase()}>{p.status}</b></span></div>)}</section></>}
function Placeholder({page}){return <div className="placeholder"><div><Sparkles/></div><h2>Модуль «{page}» готов к развитию</h2><p>Основа уже создана. На следующем этапе здесь появятся реальные подключения, данные и рабочие действия.</p><button className="primary">Развивать модуль</button></div>}
function App(){const [page,setPage]=useState('Главная');const [models,setModels]=useLocal('atlas-models-ru',seedModels);const [posts,setPosts]=useLocal('atlas-posts-ru',seedPosts);return <div className="app"><Sidebar page={page} setPage={setPage}/><main><Header page={page}/><div className="content">{page==='Главная'?<Overview models={models} setPage={setPage}/>:page==='AI-модели'?<Models models={models} setModels={setModels}/>:page==='Контент-студия'?<Studio posts={posts} setPosts={setPosts} models={models}/>:<Placeholder page={page}/>}</div></main></div>}
createRoot(document.getElementById('root')).render(<App/>);
